In [ ]:
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt
from sklearn.metrics.cluster import contingency_matrix
import numpy as np
import scipy.stats as stats
from sklearn.linear_model import LinearRegression
from sklearn import preprocessing
from sklearn.cluster import KMeans

data = pd.read_csv("happiness.csv")
data

data.info()

In [ ]:
plt.figure(figsize = (5, 4), dpi = 200)
plt.title("Pie chart of Regional indicator")
plt.pie([len(data["Regional indicator"][data["Regional indicator"]=="Western Europe"]),
         len(data["Regional indicator"][data["Regional indicator"]=="North America and ANZ"]), 
         len(data["Regional indicator"][data["Regional indicator"]=="Middle East and North Africa"]),
         len(data["Regional indicator"][data["Regional indicator"]=="Latin America and Caribbean"]),
         len(data["Regional indicator"][data["Regional indicator"]=="Central and Eastern Europe"]),
         len(data["Regional indicator"][data["Regional indicator"]=="East Asia"]),
         len(data["Regional indicator"][data["Regional indicator"]=="Southeast Asia"]),
         len(data["Regional indicator"][data["Regional indicator"]=="Commonwealth of Independent States"]),
         len(data["Regional indicator"][data["Regional indicator"]=="Sub-Saharan Africa"]),
         len(data["Regional indicator"][data["Regional indicator"]=="South Asia"])],
        labels=["Western Europe","North America and ANZ","Middle East and North Africa","Latin America and Caribbean","Central and Eastern Europe",
                "East Asia","Southeast Asia","Commonwealth of Independent States","Sub-Saharan Africa","South Asia"], autopct='%1.1f%%')
plt.savefig("Potability.png");

In [ ]:



df = data.drop('Country name',
               axis = 1) #removing character variables from dataset
df = df.drop('Regional indicator',
               axis = 1) #removing character variables from dataset
j=0 #counter
for i in df:
  plt.figure(figsize = (5, 4), dpi = 200)
  plt.title("Distribution of "+i)
  sns.distplot(data[i])
  plt.savefig(i+".png");
  j+=1



In [ ]:
main_data = data.drop('Ladder score in Dystopia',
               axis = 1) #after seeing distribution, decided to remove variable as it has one value for all objects

plt.figure(figsize = (10, 8), dpi = 200)
s=sns.pairplot(main_data, kind="scatter")
plt.show()
s.savefig("pair_scatter.png")

In [ ]:
plt.figure(figsize=(26,26), dpi= 240)
s=sns.heatmap(main_data.corr(), xticklabels=main_data.corr().columns, yticklabels=main_data.
corr().columns, cmap=sns.diverging_palette(20, 220, n=200), center=0, annot=True)
plt.show()
s.get_figure().savefig("corr.png")

In [ ]:
plt.figure(figsize=(12,10), dpi= 200)
plt.rcParams['font.size'] = '20'
sns.scatterplot(main_data["Healthy life expectancy"], main_data["Ladder score"])
plt.savefig("Lad_HLE.png")

In [ ]:
#lin_reg = LinearRegression()
#x=np.array(main_data["Ladder score"]).reshape(-1, 1) #solid
#y=np.array(main_data["Healthy life expectancy"]).reshape(-1,1) #Sulfate
#lin_reg.fit(x, y)

#lin_reg.coef_, lin_reg.intercept_

lin_reg = LinearRegression()
x=np.array(main_data["Healthy life expectancy"]).reshape(-1, 1) #solid
y=np.array(main_data["Ladder score"]).reshape(-1,1) #Sulfate
lin_reg.fit(x, y)

lin_reg.coef_, lin_reg.intercept_

(array([[0.12198682]]), array([-2.39542564]))

In [ ]:
rho = main_data[[ "Ladder score","Healthy life expectancy"]].corr()["Ladder score"]["Healthy life expectancy"]
rho,  rho**2


(0.7680994550105212, 0.5899767727874597)

In [ ]:
rho**2*100

58.997677278745975

In [ ]:
nums=np.random.choice(main_data.shape[0], size=3)
nums

array([ 80,  37, 138])

In [ ]:
x3=np.asarray(main_data["Healthy life expectancy"][nums])
x3

array([67.102, 67.906, 60.633])

In [ ]:
y3=np.asarray(main_data["Ladder score"][nums])
y3

array([5.384, 6.255, 3.819])

In [ ]:
yp3=lin_reg.coef_*x3+lin_reg.intercept_
yp3

array([[5.79013368, 5.88821108, 5.00100097]])

In [ ]:
abs(y3-yp3)

array([[0.40613368, 0.36678892, 1.18200097]])

In [ ]:

abs(y3-yp3)/abs(y3)*100, abs(y3-yp3)/abs(yp3)*100

(array([[ 7.54334476,  5.86393154, 30.950536  ]]),
 array([[ 7.01423671,  6.22920804, 23.63528776]]))

In [ ]:
res=lin_reg.predict(x)
plt.figure(figsize=(12,10), dpi= 200)
plt.rcParams['font.size'] = '20'
plt.xlabel("Healthy life expectancy")
plt.ylabel("Ladder score")
plt.title("Linear regression of Healthy life expectancy over Ladder score")
plt.plot(x, res)
plt.plot(x, [y.mean() for i in range(len(x))])
plt.scatter( main_data["Healthy life expectancy"],main_data["Ladder score"])
plt.savefig("linreg.jpeg")

In [ ]:
dif=abs(y-res)

In [ ]:
er1=100*np.mean(np.divide(dif, abs(y)))
er1

11.038402387344641

In [ ]:
er2=100*np.mean(np.divide(dif, abs(res)))
er2

10.521258495892107

In [ ]:
y.std()/y.mean()*100

19.344747656297024